language: python
python:
  - '3.5'
  - '3.6'
  - nightly
install:
  - pip install -r requirements.txt
  - python setup.py install
before_script:
  - pip install -r dev-requirements.txt
script:
  # Unittests
  - cd test && nosetests units/test_scraper.py --with-timer -v
  # End2end
  - if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then python end2end/test_api.py; fi
  - if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then python end2end/test_scraper.py; fi
branches:
  only:
    - master
