language: python
python:
  - "3.5"
  - "pypy3"
  - "3.6"
  - "nightly"
  - "3.7-dev"
install:
  - make install
before_script:
  - make dev-install
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then make test-end2end; else make test; fi
branches:
  only:
    - master
