language: python
python:
  - '3.5'
  - '3.6'
  - nightly
install:
  - pip install -r requirements.txt
  - python setup.py install
before_script:
  - pip install -r dev-requirements.txt
script:
  # Testing
  - cd test && python test.py --with-timer -v  # Unittests
  # End2end
  - python end2end/test_api.py
  - python end2end/test_scraper.py
branches:
  only:
    - master
