language: python
python:
  - "3.5"
  - "3.6"
  - "nightly"
install:
  - pip install -r requirements.txt
  - python setup.py install
before_script:
  - pip install -r dev-requirements.txt
script:
  - cd test && python test.py --with-timer -v
branches:
  only:
    - master