language: python
python:
- '3.5'
- '3.6'
- nightly
install:
- pip install -r requirements.txt
- python setup.py install
before_script:
- pip install -r dev-requirements.txt
script:
- cd test && python test.py --with-timer -v
deploy:
  provider: pypi
  user: mondeja
  password:
    secure: k7xUwqgfK+vk0WFb1yi9q3k8KtCu/ce0R0LJ4GBiCBYfC0sUgK+7pbf07R4MqEqqidsHl6mmxHPwZuX2giLTVfrCseSv3Tbx0zH8AkbjgTkerFLczIE0X6Qh8O2xDn6SmM1ZqlsFmiqF/Znz38Vw7Zc9aq3OioxRvH5pLDZLAhs0v6owqRaNaeRQBss5p/jIy/w4COSQ0N/aM4MfQBcJ6hb2a2TCvqQUf7/3D2GrPgWeAWb9Ri3s9yM9jtIted4FFQ/86BJoLmMNuJMNshkJM3fQz70mWz1H9LWVk/9V9cMNav5gIzsoMUbedbqHZvBgvm/+oq46JVjTCkU49xDQ6Kzzt4KodACUDWtpAvJUgL84r+DwiT69+RkfRx4531svfKBGGuvXKMDQLUGwJ/NeQISITMOT0mPJeOLfaVE5SRFZjTIbJYjw57C8hKe8cr4UZDJNYCEXT3yp4DBNKJpVGjEQa9xfp/2c58Y0xY05Ttr614RfgTopYRGkQBEM372kSdF+lMKqQIx0LLKIAy4TH9yrYvfBDAYcPS54F/H8i9+EtgxUeUM6zuhW0o0fL9K1TDTvBBHk2+ZhQmcUF2zYv4OOznLPKzQl+vM67HFOQV7IGJfIC2d3doAQoAjazdAlyV9nEiS8jC3qnJHWO6xo6Cb7yW8cWEcK1+t/RWvn9mY=
branches:
  only:
  - master
