language: python
os:
  - linux
  - osx
python:
  - '3.6'
  - nightly
install:
  - pip install -r requirements.txt
  - python setup.py install
before_script:
  - pip install -r dev-requirements.txt
script:
  # Unittests
  - cd tests && nosetests units/test_scraper.py --with-timer -v
  # End2end
  - python end2end/test_scraper.py
after_success:
  - coveralls
branches:
  only:
    - master
